---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: "Add Tenant {{apic_tenant}}"
    aci_tenant:
      tenant: "{{apic_tenant}}"
      state: present
      host: aci01.mgmt.siriussdx.com
      validate_certs: false
