---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: "Add Tenant {{apic_tenant}}"
    aci_tenant:
      tenant: "{{apic_tenant}}"
      state: present
      ansible_connection: local
      host: aci01.mgmt.siriussdx.com
      username: "{{ ansible_env.ANSIBLE_NET_USERNAME }}"
      password: "{{ ansible_env.ANSIBLE_NET_PASSWORD }}"
      validate_certs: false
