---
- hosts: localhost
  gather_facts: no
  vars: 
   host: aci01.mgmt.siriussdx.com
   username: "{{ ansible_env.ANSIBLE_NET_USERNAME }}" 
   state: present 
   password: "{{ ansible_env.ANSIBLE_NET_PASSWORD }}"
  tasks:
  - name: "Add Tenant {{apic_tenant}}"
    aci_tenant:
      tenant: "{{apic_tenant}}"
      state: present
      ansible_connection: local
      host: aci01.mgmt.siriussdx.com
      validate_certs: false
