---
- hosts: localhost
  gather_facts: no
- name: Ensure tenant customer-xyz exists
  aci_tenant:
    host: aci01
    username: admin
    password: Vinson0)

    tenant: customer-xyz
    description: Customer XYZ
    state: present
