---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: aci01.mgmt.siriussdx.com
  connection: local
  gather_facts: False
  vars:
   host: aci01.mgmt.siriussdx.com
   username: username
   state: present 
   password: password

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        host: aci01.mgmt.siriussdx.com
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: anisble01
        description: "Tenant Created Using Ansible"
