---
- name: ENSURE APPLICATION CONFIGURATION EXISTS
  hosts: aci01.mgmt.siriussdx.com
  connection: local
  gather_facts: False
  vars:
    hostname: '{{ inventory_hostname }}'
    username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
    password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
    validate_certs: no

  tasks:
    - name: ENSURE APPLICATIONS TENANT EXISTS
      aci_tenant:
        host: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        description: "Tenant Created Using Ansible"
        
