---
- name: Query all tenants
  hosts: aci01.mgmt.siriussdx.com
  connection: local
  gather_facts: False
  vars:
    hostname: '{{ inventory_hostname }}'
    username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
    password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
    validate_certs: no
  task:
- name: Query all tenants
   aci_tenant:
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    state: query
 
